os : linux

language : go

go:
  - 1.14.3
  
services:
  - postgresql
  - docker
  
script:
  - go test -v ./...
  # Build the code
  - CGO_ENABLED=0 GOARCH=amd64 go build -o ms_demo
  - echo "$REGISTRY_PASSWORD" | docker login --username $REGISTRY_USER --password-stdin
  - docker build -f Dockerfile -t dini9596/ms_demo:latest ./
  - GIT_SHA="$(git rev-parse --short HEAD)"
  - docker tag dini9596/ms_demo:latest dini9596/ms_demo:$GIT_SHA
  - docker push dini9596/ms_demo:latest
  - docker push dini9596/ms_demo:$GIT_SHA
